# VehicleSpec
# Query the specification of a vehicle by unique id.
# Service: /Service_MoraiVehicleSpec

VehicleSpecIndex request  # Unique id of the requested vehicle
---
VehicleSpec response      # Vehicle specification data
