#!/usr/bin/env python3
"""
Generate documentation pages for MORAI ROS2 messages and services.
"""

import os
import re
from pathlib import Path

# Base paths
REPO_ROOT = Path(__file__).parent.parent
MSG_DIR = REPO_ROOT / "msg"
SRV_DIR = REPO_ROOT / "srv"
DOCS_MSG_DIR = REPO_ROOT / "docs" / "messages"
DOCS_SRV_DIR = REPO_ROOT / "docs" / "services"
MKDOCS_YML = REPO_ROOT / "mkdocs.yml"

# Ensure docs directories exist
DOCS_MSG_DIR.mkdir(parents=True, exist_ok=True)
DOCS_SRV_DIR.mkdir(parents=True, exist_ok=True)

# Curated message categories: (category title, blurb, [member message names]).
# Ordered. Messages present in the repo but not listed here are placed in a trailing
# "Other Messages" group, and listed messages absent from a given ref are skipped --
# so any message set still yields a valid nav and overview. This lets the same tooling
# build every version (dev + historical release tags).
CATEGORIES = [
    ("Control Messages", "Messages for controlling vehicle motion and behavior:",
     ["CtrlCmd"]),
    ("Vehicle Status", "Messages containing real-time vehicle state information:",
     ["EgoVehicleStatus", "VehicleSpec", "VehicleSpecIndex", "Lamps"]),
    ("Collision & Safety", "Messages related to collision detection and safety:",
     ["CollisionData", "VehicleCollision", "VehicleCollisionData"]),
    ("Traffic & Infrastructure", "Messages for traffic lights and infrastructure control:",
     ["GetTrafficLightStatus", "SetTrafficLight", "TrafficLightIndex", "TrafficLightInfo",
      "IntersectionControl", "IntersectionStatus"]),
    ("Perception & Sensors", "Messages for sensor data and object detection:",
     ["ObjectStatus", "ObjectStatusList", "RadarDetection", "RadarDetections",
      "GPSMessage", "SensorPosControl"]),
    ("Simulation Control", "Messages for simulator configuration and management:",
     ["MoraiSimProcHandle", "MoraiSimProcStatus", "MoraiSrvResponse", "ScenarioLoad",
      "EventInfo", "ReplayInfo", "SaveSensorData"]),
    ("Ghost & NPC", "Messages for non-player character control:",
     ["GhostCmd", "NpcGhostCmd", "NpcGhostInfo"]),
    ("Map", "Messages for map specifications:",
     ["MapSpec"]),
    ("Multi-Vehicle", "Messages for multi-vehicle scenarios:",
     ["MultiEgoSetting"]),
]

# Services render as a flat list in the nav. Keep this curated order first (extras
# appended alphabetically), and map file stem -> display label where they differ.
SERVICE_ORDER = ["EventCmd", "MapSpec", "ScenarioLoad", "MoraiSimProc",
                 "TrafficLightInfo", "VehicleSpec"]
SERVICE_LABELS = {"TrafficLightInfo": "TLInfo"}

# Curated service groupings for the services overview page: (group title, [members]).
SERVICE_CATEGORIES = [
    ("Event Management", ["EventCmd"]),
    ("Map & Environment", ["MapSpec", "TrafficLightInfo"]),
    ("Simulation Management", ["MoraiSimProc", "ScenarioLoad"]),
    ("Vehicle Configuration", ["VehicleSpec"]),
]

# Marker delimiting the auto-generated region inside the overview index.md pages.
AUTOGEN_BEGIN = "<!-- AUTOGEN:BEGIN (overview list generated by generate_docs.py) -->"
AUTOGEN_END = "<!-- AUTOGEN:END -->"


def parse_header_block(path):
    """Parse the leading comment block of a .msg/.srv file.

    Convention (matches the annotated definitions):
        # <Title>
        # <description line(s)>
        # Topic: /some_topic      (optional)
        # Service: /some_service  (optional)
        <blank line>
        <fields...>

    Returns a dict with 'description', 'topic' and 'service' keys.
    """
    description_lines = []
    topic = None
    service = None
    first = True

    with open(path, 'r', encoding='utf-8') as f:
        for raw in f:
            line = raw.rstrip()
            # The header block ends at the first blank or non-comment line.
            if not line.strip() or not line.strip().startswith('#'):
                break
            text = line.strip()[1:].strip()
            if first:
                # Skip the title line (the message/service name itself).
                first = False
                continue
            lower = text.lower()
            if lower.startswith('topic:'):
                topic = text.split(':', 1)[1].strip()
            elif lower.startswith('service:'):
                service = text.split(':', 1)[1].strip()
            elif text:
                description_lines.append(text)

    return {
        'description': ' '.join(description_lines).strip(),
        'topic': topic,
        'service': service,
    }


def render_header_section(header):
    """Render description / topic / service metadata as markdown."""
    out = ""
    if header['description']:
        out += f"{header['description']}\n\n"
    if header['topic']:
        out += f"**Topic**: `{header['topic']}`\n\n"
    if header['service']:
        out += f"**Service**: `{header['service']}`\n\n"
    return out


def parse_msg_file(msg_path):
    """Parse a .msg file and return fields with comments."""
    fields = []
    current_comment = []
    
    with open(msg_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip()
            
            # Skip empty lines
            if not line:
                current_comment = []
                continue
                
            # Handle comments
            if line.strip().startswith('#'):
                current_comment.append(line.strip()[1:].strip())
                continue
            
            # Parse field
            if line.strip():
                parts = line.split()
                if len(parts) >= 2:
                    field_type = parts[0]
                    field_name = parts[1]
                    
                    # Check for array notation
                    array_info = ""
                    if '[' in field_name:
                        field_name, array_part = field_name.split('[', 1)
                        array_info = f" [{array_part}"
                    
                    # Inline comment
                    inline_comment = ""
                    if '#' in line:
                        inline_comment = line.split('#', 1)[1].strip()
                    
                    comment = inline_comment if inline_comment else ' '.join(current_comment)
                    
                    fields.append({
                        'type': field_type,
                        'name': field_name,
                        'array': array_info,
                        'comment': comment
                    })
                    current_comment = []
    
    return fields


def parse_srv_file(srv_path):
    """Parse a .srv file and return request/response fields."""
    request_fields = []
    response_fields = []
    current_section = request_fields
    current_comment = []
    
    with open(srv_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip()
            
            # Check for separator
            if line.strip() == '---':
                current_section = response_fields
                current_comment = []
                continue
            
            # Skip empty lines
            if not line:
                current_comment = []
                continue
                
            # Handle comments
            if line.strip().startswith('#'):
                current_comment.append(line.strip()[1:].strip())
                continue
            
            # Parse field
            if line.strip():
                parts = line.split()
                if len(parts) >= 2:
                    field_type = parts[0]
                    field_name = parts[1]
                    
                    # Check for array notation
                    array_info = ""
                    if '[' in field_name:
                        field_name, array_part = field_name.split('[', 1)
                        array_info = f" [{array_part}"
                    
                    # Inline comment
                    inline_comment = ""
                    if '#' in line:
                        inline_comment = line.split('#', 1)[1].strip()
                    
                    comment = inline_comment if inline_comment else ' '.join(current_comment)
                    
                    current_section.append({
                        'type': field_type,
                        'name': field_name,
                        'array': array_info,
                        'comment': comment
                    })
                    current_comment = []
    
    return request_fields, response_fields


def generate_msg_doc(msg_name, msg_path):
    """Generate markdown documentation for a message."""
    fields = parse_msg_file(msg_path)
    
    doc = f"# {msg_name}\n\n"
    doc += f"**Message Type**: `morai_msgs/msg/{msg_name}`\n\n"
    doc += render_header_section(parse_header_block(msg_path))

    # Read raw content
    with open(msg_path, 'r', encoding='utf-8') as f:
        raw_content = f.read()
    
    doc += "## Message Definition\n\n"
    doc += "```\n"
    doc += raw_content
    if raw_content and not raw_content.endswith('\n'):
        doc += "\n"
    doc += "```\n\n"
    
    if fields:
        doc += "## Field Descriptions\n\n"
        doc += "| Field | Type | Description |\n"
        doc += "|-------|------|-------------|\n"
        
        for field in fields:
            type_with_array = f"{field['type']}{field['array']}" if field['array'] else field['type']
            comment = field['comment'] if field['comment'] else "-"
            doc += f"| `{field['name']}` | `{type_with_array}` | {comment} |\n"
        doc += "\n"
    
    doc += "## Usage Example\n\n"
    doc += "### Python\n\n"
    doc += "```python\n"
    doc += f"from morai_msgs.msg import {msg_name}\n\n"
    doc += f"# Create message\n"
    doc += f"msg = {msg_name}()\n"
    if fields:
        for i, field in enumerate(fields[:3]):  # Show first 3 fields as example
            default_val = "0.0" if "float" in field['type'] else "0" if "int" in field['type'] else "''"
            doc += f"msg.{field['name']} = {default_val}\n"
    doc += "```\n\n"
    
    doc += "### C++\n\n"
    doc += "```cpp\n"
    doc += f"#include <morai_msgs/msg/{msg_name.lower()}.hpp>\n\n"
    doc += f"// Create message\n"
    doc += f"auto msg = morai_msgs::msg::{msg_name}();\n"
    if fields:
        for i, field in enumerate(fields[:3]):  # Show first 3 fields as example
            default_val = "0.0" if "float" in field['type'] else "0" if "int" in field['type'] else '""'
            doc += f"msg.{field['name']} = {default_val};\n"
    doc += "```\n\n"
    
    return doc


def generate_srv_doc(srv_name, srv_path):
    """Generate markdown documentation for a service."""
    request_fields, response_fields = parse_srv_file(srv_path)
    
    doc = f"# {srv_name}\n\n"
    doc += f"**Service Type**: `morai_msgs/srv/{srv_name}`\n\n"
    doc += render_header_section(parse_header_block(srv_path))

    # Read raw content
    with open(srv_path, 'r', encoding='utf-8') as f:
        raw_content = f.read()
    
    doc += "## Service Definition\n\n"
    doc += "```\n"
    doc += raw_content
    if raw_content and not raw_content.endswith('\n'):
        doc += "\n"
    doc += "```\n\n"
    
    if request_fields:
        doc += "## Request Fields\n\n"
        doc += "| Field | Type | Description |\n"
        doc += "|-------|------|-------------|\n"
        
        for field in request_fields:
            type_with_array = f"{field['type']}{field['array']}" if field['array'] else field['type']
            comment = field['comment'] if field['comment'] else "-"
            doc += f"| `{field['name']}` | `{type_with_array}` | {comment} |\n"
        doc += "\n"
    
    if response_fields:
        doc += "## Response Fields\n\n"
        doc += "| Field | Type | Description |\n"
        doc += "|-------|------|-------------|\n"
        
        for field in response_fields:
            type_with_array = f"{field['type']}{field['array']}" if field['array'] else field['type']
            comment = field['comment'] if field['comment'] else "-"
            doc += f"| `{field['name']}` | `{type_with_array}` | {comment} |\n"
        doc += "\n"
    
    doc += "## Usage Example\n\n"
    doc += "### Python\n\n"
    doc += "```python\n"
    doc += "import rclpy\n"
    doc += "from rclpy.node import Node\n"
    doc += f"from morai_msgs.srv import {srv_name}\n\n"
    doc += "class ServiceClient(Node):\n"
    doc += "    def __init__(self):\n"
    doc += "        super().__init__('service_client')\n"
    doc += f"        self.client = self.create_client({srv_name}, '/service_name')\n"
    doc += "        \n"
    doc += "    def call_service(self):\n"
    doc += f"        request = {srv_name}.Request()\n"
    doc += "        # Set request fields\n"
    doc += "        future = self.client.call_async(request)\n"
    doc += "        return future\n"
    doc += "```\n\n"
    
    doc += "### C++\n\n"
    doc += "```cpp\n"
    doc += "#include <rclcpp/rclcpp.hpp>\n"
    doc += f"#include <morai_msgs/srv/{srv_name.lower()}.hpp>\n\n"
    doc += "class ServiceClient : public rclcpp::Node {\n"
    doc += "public:\n"
    doc += "    ServiceClient() : Node(\"service_client\") {\n"
    doc += f"        client_ = this->create_client<morai_msgs::srv::{srv_name}>(\n"
    doc += "            \"/service_name\");\n"
    doc += "    }\n"
    doc += "    \n"
    doc += "    void call_service() {\n"
    doc += f"        auto request = std::make_shared<morai_msgs::srv::{srv_name}::Request>();\n"
    doc += "        // Set request fields\n"
    doc += "        auto future = client_->async_send_request(request);\n"
    doc += "    }\n\n"
    doc += "private:\n"
    doc += f"    rclcpp::Client<morai_msgs::srv::{srv_name}>::SharedPtr client_;\n"
    doc += "};\n"
    doc += "```\n\n"
    
    return doc


def clean_generated_docs():
    """Remove previously generated per-item pages (keeping the hand-written index.md).

    Without this, building an older release on top of the current docs/ tree would leave
    stale pages for messages that no longer exist in that release.
    """
    for docs_dir in (DOCS_MSG_DIR, DOCS_SRV_DIR):
        for md in docs_dir.glob("*.md"):
            if md.name != "index.md":
                md.unlink()


def build_nav(msg_names, srv_names):
    """Build the mkdocs `nav:` block from the items that were actually generated."""
    lines = ["nav:", "  - Home: index.md", "  - Messages:",
             "    - Overview: messages/index.md"]

    remaining = set(msg_names)
    for category, _blurb, members in CATEGORIES:
        present = [m for m in members if m in remaining]
        if not present:
            continue
        lines.append(f"    - {category}:")
        for m in present:
            lines.append(f"      - {m}: messages/{m}.md")
            remaining.discard(m)
    leftovers = sorted(remaining)  # messages not in the curated map (e.g. other releases)
    if leftovers:
        lines.append("    - Other Messages:")
        for m in leftovers:
            lines.append(f"      - {m}: messages/{m}.md")

    lines.append("  - Services:")
    lines.append("    - Overview: services/index.md")
    ordered_srv = [s for s in SERVICE_ORDER if s in srv_names]
    ordered_srv += sorted(s for s in srv_names if s not in SERVICE_ORDER)
    for s in ordered_srv:
        lines.append(f"    - {SERVICE_LABELS.get(s, s)}: services/{s}.md")

    return "\n".join(lines) + "\n"


def write_nav(nav_text):
    """Replace the top-level `nav:` block in mkdocs.yml with the generated one."""
    content = MKDOCS_YML.read_text(encoding="utf-8")
    # Match `nav:` at the start of a line through to (but not including) the next
    # top-level key (a line that begins with a non-whitespace character).
    pattern = re.compile(r"^nav:.*?(?=^\S)", re.DOTALL | re.MULTILINE)
    if not pattern.search(content):
        raise RuntimeError("Could not locate a `nav:` block in mkdocs.yml")
    new_content = pattern.sub(nav_text + "\n", content, count=1)
    MKDOCS_YML.write_text(new_content, encoding="utf-8")
    print(f"  Updated nav in {MKDOCS_YML.relative_to(REPO_ROOT)}")


def _item_line(name, descriptions):
    """Render one overview bullet, appending the description when one is available."""
    desc = descriptions.get(name, "").strip()
    return f"- **[{name}]({name}.md)**" + (f" - {desc}" if desc else "")


def build_messages_overview(msg_names, descriptions):
    """Build the auto-generated body of docs/messages/index.md."""
    out = [f"This section contains documentation for all {len(msg_names)} ROS2 message "
           f"definitions in the `morai_msgs` package.", "", "## Message Categories", ""]
    remaining = set(msg_names)
    for title, blurb, members in CATEGORIES:
        present = [m for m in members if m in remaining]
        if not present:
            continue
        out += [f"### {title}", blurb, ""]
        out += [_item_line(m, descriptions) for m in present]
        out.append("")
        remaining.difference_update(present)
    leftovers = sorted(remaining)
    if leftovers:
        out += ["### Other Messages", "Additional messages in this release:", ""]
        out += [_item_line(m, descriptions) for m in leftovers]
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def build_services_overview(srv_names, descriptions):
    """Build the auto-generated body of docs/services/index.md."""
    out = [f"This section contains documentation for all {len(srv_names)} ROS2 service "
           f"definitions in the `morai_msgs` package.", "", "## Available Services", ""]
    remaining = set(srv_names)
    for title, members in SERVICE_CATEGORIES:
        present = [s for s in members if s in remaining]
        if not present:
            continue
        out += [f"### {title}", ""]
        out += [_item_line(s, descriptions) for s in present]
        out.append("")
        remaining.difference_update(present)
    leftovers = sorted(remaining)
    if leftovers:
        out += ["### Other Services", ""]
        out += [_item_line(s, descriptions) for s in leftovers]
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def write_overview(index_path, body):
    """Replace the AUTOGEN region of an overview index.md with freshly built content."""
    content = index_path.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(AUTOGEN_BEGIN) + r".*?" + re.escape(AUTOGEN_END), re.DOTALL)
    block = f"{AUTOGEN_BEGIN}\n\n{body}\n{AUTOGEN_END}"
    if not pattern.search(content):
        raise RuntimeError(
            f"Could not find AUTOGEN markers in {index_path.relative_to(REPO_ROOT)}")
    index_path.write_text(pattern.sub(lambda _m: block, content, count=1), encoding="utf-8")
    print(f"  Updated overview in {index_path.relative_to(REPO_ROOT)}")


def main():
    """Generate all documentation pages."""
    clean_generated_docs()
    print("Generating message documentation...")

    # Generate message docs
    msg_count = 0
    msg_names = []
    descriptions = {}  # item name -> short description from its header block
    for msg_file in sorted(MSG_DIR.glob("*.msg")):
        msg_name = msg_file.stem
        doc_content = generate_msg_doc(msg_name, msg_file)

        doc_path = DOCS_MSG_DIR / f"{msg_name}.md"
        with open(doc_path, 'w', encoding='utf-8') as f:
            f.write(doc_content)

        print(f"  Created: {doc_path.relative_to(REPO_ROOT)}")
        msg_names.append(msg_name)
        descriptions[msg_name] = parse_header_block(msg_file)['description']
        msg_count += 1

    print(f"\nGenerated {msg_count} message documentation pages.")

    # Generate service docs
    print("\nGenerating service documentation...")
    srv_count = 0
    srv_names = []
    for srv_file in sorted(SRV_DIR.glob("*.srv")):
        srv_name = srv_file.stem
        doc_content = generate_srv_doc(srv_name, srv_file)

        doc_path = DOCS_SRV_DIR / f"{srv_name}.md"
        with open(doc_path, 'w', encoding='utf-8') as f:
            f.write(doc_content)

        print(f"  Created: {doc_path.relative_to(REPO_ROOT)}")
        srv_names.append(srv_name)
        descriptions[srv_name] = parse_header_block(srv_file)['description']
        srv_count += 1

    print(f"\nGenerated {srv_count} service documentation pages.")

    # Regenerate the navigation and overview pages so they always match the
    # message/service set that was just built (required for building historical
    # releases whose definition sets differ from the current one).
    print("\nUpdating navigation and overview pages...")
    write_nav(build_nav(msg_names, srv_names))
    write_overview(DOCS_MSG_DIR / "index.md", build_messages_overview(msg_names, descriptions))
    write_overview(DOCS_SRV_DIR / "index.md", build_services_overview(srv_names, descriptions))

    print(f"\nTotal: {msg_count + srv_count} documentation pages created!")
    print("\nTo view the documentation:")
    print("  1. Install dependencies: pip install mkdocs-material")
    print("  2. Run local server: mkdocs serve")
    print("  3. Open browser: http://127.0.0.1:8000")


if __name__ == "__main__":
    main()
